import Head from "next/head";
import AppLayout from "@/components/AppLayout";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  const toggleDarkMode = () => {
    setDarkMode((prevDarkMode) => !prevDarkMode);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${darkMode ? "" : "light"} bg-mainDark light:light`}>
        <AppLayout darkMode={darkMode} toggleDarkMode={toggleDarkMode} />
      </main>
    </>
  );
}
