import Head from "next/head";
import AppLayout from "@/components/AppLayout";
import { useEffect, useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const onToggle = () => {
    setDarkMode(!darkMode);
  };

  useEffect(() => {
    if (darkMode) {
      document.body.classList.add("dark");
    } else {
      document.body.classList.remove("dark");
    }
  }, [darkMode]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo-mobile.svg" />
      </Head>
      <main className={`bg-white dark:bg-mainDark`}>
        <AppLayout darkMode={darkMode} toggleDarkMode={onToggle} />
      </main>
    </>
  );
}
